# Generated by Django 4.0.3 on 2022-03-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='app1/static/app1/upload_files/', verbose_name='Название файла')),
                ('file_create', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False, verbose_name='Регистрация изменений')),
            ],
            options={
                'verbose_name': 'Обработанный файл',
                'verbose_name_plural': 'Обработанные файлы',
                'db_table': 'file_results',
            },
        ),
        migrations.CreateModel(
            name='ImageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.ImageField(upload_to='app1/static/app1/img/', verbose_name='Название диаграммы')),
                ('img_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Диаграмма результатов',
                'verbose_name_plural': 'Диаграммы результатов',
                'db_table': 'img_results',
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='app1/static/app1/download_files/', verbose_name='Название файла')),
                ('file_create', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False, verbose_name='Регистрация изменений')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
                'db_table': 'import_files',
            },
        ),
        migrations.CreateModel(
            name='MailFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_mail', models.CharField(max_length=100, verbose_name='E-mails')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CSV E-mail',
                'verbose_name_plural': 'CSV E-mails',
                'db_table': 'file_mails',
            },
        ),
        migrations.CreateModel(
            name='MailForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_mail', models.CharField(max_length=100, verbose_name='E-mails')),
                ('time_create', models.CharField(max_length=100, verbose_name='Время записи данных')),
            ],
            options={
                'verbose_name': 'E-mail',
                'verbose_name_plural': 'E-mails',
                'db_table': 'input_mails',
            },
        ),
    ]
